### ISSUE TITLE
Loading page sketch for games

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#19]

**Comment by carolinhr** [comment]
[loading page.pdf](https://github.com/user-attachments/files/17484797/loading.page.pdf)

**Comment by carolinhr** [comment]
Assets

Large Star
![137C7D37-5D0F-443A-B653-3F03C10BA46D](https://github.com/user-attachments/assets/18022481-b553-4069-a798-8c94d7b4e364)

Small star
![C527D74E-E778-4F9A-85F2-21EDB0378A3F](https://github.com/user-attachments/assets/b624dc05-f3aa-4e2e-bc01-df84991229c4)
